### PR TITLE
Update the README to add a bit more info about getting started with t…

### PR DESCRIPTION
**Pull request by alxndrsn**
…he OS.

### CODE REVIEW

**Comment by garethbowen** [comment]
I was thinking it would be useful to have "Launch your browser and go to http://xxx.xxx.xxx.xxx to use Medic Mobile" on the black screen because that's not obvious.

**Comment by alxndrsn** [comment]
@garethbowen nice idea!

**Comment by mandric** [comment]
Type xxx.xxx.xxx.xxx into your browser and press enter. ;)

**Comment by browndav** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
