### PR TITLE
Merge INTERNALS documentation into README

### PR DESCRIPTION
**Pull request by alxndrsn**
Should make it easier to find useful documentation.

### CODE REVIEW

**Comment by estellecomment** [comment]
+1 for documentation action! :)

There's also a 3rd file, packages.md, in the same situation. I think it would be better to link internals.md and packages.md from README.md (rather than copy it over).

Then we can push everything to medic.github.io as pretty docs, so separate pages are more organized.

**Comment by alxndrsn** [comment]
Good spot `packages.md`.  -1 for leaving them separate - if I want to find information, I want to search it (as text), and separate files make this difficult, especially if the name of the file does not related to the specific subject which is relevant to me.

**Comment by estellecomment** [comment]
+1 for renaming INTERNALS.md to something better.

I get your point but I think as size of doc increases, having everything in one giant file is going to be hard to use (same problem with the giant app-settings page, it's huge therefore unusable)

If the information is sorted in files/pages that make sense, with a sidebar for navigation, then would you be able to find the file you want?
Or is the issue that you want to be able to ctrl-F or grep for all your search needs? If it's important I can look into github pages' search and if it's any good.

**Comment by alxndrsn** [comment]
> I get your point but I think as size of doc increases, having everything in one giant file is going to be hard to use (same problem with the giant app-settings page, it's huge therefore unusable)

When this actually becomes a problem, splitting it would be useful.  I don't think comparing to the app-settings page is very useful, as no browser should have a problem loading a few K of text, whereas app settings is a big blob of JSON that gets a big nested DOM built for it.

> If the information is sorted in files/pages that make sense, with a sidebar for navigation, then would you be able to find the file you want?  Or is the issue that you want to be able to ctrl-F or grep for all your search needs?

As long as the words that I expect to relate to a subject also appear in the sidebar, then this would be fine.  This seems unlikely to me, so being able to search the full text of the documentation in one go makes everything much simpler.

> If it's important I can look into github pages' search and if it's any good.

If you're referring to github's wiki search, then the answer is that it doesn't exist, or perhaps it's just very bad - I've certainly had to clone wikis (they are git repos) and then `grep` the source tree to get useful information out of them in the past.  As _github pages_ are just static websites, I imagine that you could run google custom search over them, but this seems much more complicated than just merging the files.

**Comment by estellecomment** [comment]
> no browser should have a problem loading a few K of text

In this case I don't mean browser loading, I mean usability. Even if it loads instantly, it's a mess to navigate, you don't remember what's where, and you end up only using ctrl-F, which kills any discoverability (i.e. you can only ctrl-F for what you already know, so you can't stumble on what you don't know).

I've tried other github sites to see how they were indexed by Google, and I don't get great results. :( Not good for search here.

I would still prefer separate pages with navigation as my interface of choice (without navigation menu, it's hard to find pages, not so good), and resort to a github repo search if I want to search across the whole doc.

**Comment by ghost** [comment]
Merged (from the most recent copy), a half-year late. Apologies, that is terribly lame.

**Pull request closed without merging**
